LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

ifeq ($(TARGET_ARCH),arm)
LOCAL_CFLAGS += -DANDROID_ARM
LOCAL_ARM_MODE := arm
endif

ifeq ($(TARGET_ARCH),x86)
LOCAL_CFLAGS +=  -DANDROID_X86
endif

ifeq ($(TARGET_ARCH),mips)
LOCAL_CFLAGS += -DANDROID_MIPS
endif

LOCAL_MODULE    := libretro

ROOT_DIR := ../..
CORE_DIR := $(ROOT_DIR)/src

include $(ROOT_DIR)/Makefile.common

LOCAL_SRC_FILES    = $(SOURCES_C)

LOCAL_CFLAGS += -O3 -DHAVE_LIBMAD -DMUSIC_SUPPORT -DINLINE=inline -DHAVE_INTTYPES_H -DHAVE_MEMORY_H -D__LIBRETRO__ -DFPM_DEFAULT -DSIZEOF_INT=4 -DSIZEOF_LONG=4 -DSIZEOF_LONG_LONG=8 -DFRONTEND_SUPPORTS_RGB565

include $(BUILD_SHARED_LIBRARY)
